# Generated by Django 3.1.7 on 2021-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20210327_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='site_url',
            field=models.URLField(null=True),
        ),
    ]
