# Generated by Django 3.1.7 on 2021-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_slider_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
